
image: gitpod/workspace-full

tasks:
  - name: Install Crystal & Run Tests
    before: curl -fsSL https://crystal-lang.org/install.sh | sudo bash
    init: make

vscode:
  extensions:
    - crystal-lang-tools.crystal-lang
